### ISSUE TITLE
Overview page

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#15]
## Introduction 

Modifying contents and features of the page where users can have a overview of the calculus that have been made

**Comment by maloufabmob** [comment]
- [x] Add a feature that allow users to separate the results by transport category (whether it is an individual transport or a collective one) 
- [x] Allow users to export the results in .csv 
- [x] Allow users to export the results in .pdf 
- [x] Add % of increase and decrease on the graphs
- [x] Add a feature to publish the data

**Comment by TTalex** [comment]
Instead of a feature to separate de results by transport category, I opted for a selection of categories to display. That way, users are free to choose. This selection takes part in a new option menu allowing the following configurations:
* Choice of transport categories
* Choice between TTW and WTW for the GHG emission graph
* Choice of which legends are displayed: % increase and/or chart values

The option menu is hidden by default and is displayed upon clicking on its header. I have also added a 📌 button to stick the menu on top of the page, which allows for accessibility even after scrolling. This might be a terrible UX, but it helped to visualize changes in real-time.
![Image](https://user-images.githubusercontent.com/7023229/183958348-8d695028-0b72-4537-b11c-427e00e890a7.png)


I have also added an export to CSV, that includes both computed outputs and user inputs, here is a sample export: [MGP_2_export (4).csv](https://github.com/fabmob/myc-emissions-calculator/files/9301844/MGP_2_export.4.csv) (sources aren't filled correctly)
In theory, this data can be used as an input to the transport database, but it's not quite copy-pastable yet.

Finally, I added a message for projects still in the draft state, with a link to validate.
![Image](https://user-images.githubusercontent.com/7023229/183958442-a95ba0a6-ea13-47ca-99b5-afc78ee0104c.png)
