### ISSUE TITLE
Freight

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#18]
## Introduction 

Adding the freight categories in the tool

**Comment by maloufabmob** [comment]
- [x] Add categories 
- [x] Add graphs
- [x] Add emission calculation based on the activity

_-> mostly from the excel-based tool_

**Comment by maloufabmob** [comment]
to add a custom category, it will be then necessary to ask if it is freight or passengers

**Comment by TTalex** [comment]
It looks like the only differences between freight and passengers are the units, passengers or tons, and the name of the categories.
Only one graph needs to be added: Modal split for transport. It is computed the same way (vkt * what's being transported) but the result is tons-kilometer (tkm) instead of person-kilometer (pkm)

I added said graph and new categories (using available emojis). Custom categories also require a type to be specified.

Should we also divide the other graphs ? Or add a filter to only display passenger or freight data ?

**Comment by TTalex** [comment]
See #34 for a followup on visualizations questions.
